# Production environment configuration
replicaCount: 3

image:
  repository: shahidkhan48/nodejs-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  targetPort: 3000

ingress:
  hosts:
    - host: your-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nodejs-tls
      hosts:
        - your-domain.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "3000"

# Docker registry credentials for prod
imageCredentials:
  registry: docker.io
  username: shahidkhan48
  password: your-password

# Production configuration
config:
  NODE_ENV: production
  PORT: "3000"
  API_URL: "https://api.example.com"
  DATABASE_URL: "mongodb://prod-db:27017/myapp"