package com.ninjacart.nfcservice.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum CommandTypeEnum {
  INITIATE_CHAT_REQUEST,
  WELCOME_MESSAGE,
  ORDER_REQUEST_APPROVAL,
  ORDER_CREATED,
  ORDER_UPDATE_STATUS,
  MODIFY_ORDER,
  MODIFY_ORDER_CREATED,
  RAISE_DISPUTE,
  INITIATE_CHAT_REQUEST_AUDIT,
  ORDER_REQUEST_APPROVAL_AUDIT,
  CATALOG_SHARE,

  CATALOG_DELETE,
  FORWARD_CATALOG,
  ORDER_MODIFY_APPROVAL_AUDIT;



}
